
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 10;
  public static final int LT = 12;
  public static final int OVER = 11;
  public static final int ELSE = 3;
  public static final int PLUS = 8;
  public static final int NOTEQ = 16;
  public static final int INT = 5;
  public static final int SEMI = 19;
  public static final int WHILE = 4;
  public static final int RETURN = 7;
  public static final int ERROR = 29;
  public static final int IF = 2;
  public static final int GT = 13;
  public static final int ID = 27;
  public static final int NUM = 28;
  public static final int EQUALS = 17;
  public static final int RCURVED = 22;
  public static final int COMMA = 20;
  public static final int RSQUIG = 26;
  public static final int LTEQ = 14;
  public static final int EOF = 0;
  public static final int LSQUARE = 23;
  public static final int MINUS = 9;
  public static final int error = 1;
  public static final int ASSIGN = 18;
  public static final int LSQUIG = 25;
  public static final int RSQUARE = 24;
  public static final int GTEQ = 15;
  public static final int LCURVED = 21;
  public static final int VOID = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "ELSE",
  "WHILE",
  "INT",
  "VOID",
  "RETURN",
  "PLUS",
  "MINUS",
  "TIMES",
  "OVER",
  "LT",
  "GT",
  "LTEQ",
  "GTEQ",
  "NOTEQ",
  "EQUALS",
  "ASSIGN",
  "SEMI",
  "COMMA",
  "LCURVED",
  "RCURVED",
  "LSQUARE",
  "RSQUARE",
  "LSQUIG",
  "RSQUIG",
  "ID",
  "NUM",
  "ERROR"
  };
}

